/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background-02": "#fff",
        "neutral-100": "#080e14",
        "primary-60": "#007bff",
        "neutral-70": "#52565b",
        gray: "#211e1f",
        "neutral-40": "#9c9fa1",
        gold: "#fcde5a",
        "background-01": "#00364e",
        black: "#000",
        "neutral-60": "#6b6e72",
        "background-03": "#f1f2f6",
        lightgray: "#cecfd0",
        darkslategray: "#004463",
        "tertiary-60": "#ff7a00",
        "primary-20": "#cce5ff",
        royalblue: "#027dff",
        "secondary-50": "#fde57b",
        "background-04": "#d4e9ff",
        whitesmoke: {
          "100": "#f3f3f3",
          "200": "#ededed",
        },
        lavenderblush: "#ffedf0",
        honeydew: "#f2ffed",
        seashell: "#fff3ec",
        cornsilk: "#fef8de",
        "success-60": "#d6f4de",
        forestgreen: "#169c38",
        "tertiary-10": "#ffe4cc",
        indianred: "#d85a6e",
        lightsalmon: "#ffad7a",
        darkseagreen: "#8ec37a",
        aliceblue: "#e6f2ff",
        crimson: "#ea2424",
      },
      spacing: {},
      fontFamily: {
        "body-02-semibold": "Poppins",
        montserrat: "Montserrat",
      },
      borderRadius: {
        xl: "20px",
        "22xl-7": "41.7px",
        "6xl-2": "25.2px",
      },
    },
    fontSize: {
      base: "16px",
      lg: "18px",
      "13xl": "32px",
      "29xl": "48px",
      "5xl": "24px",
      xl: "20px",
      "45xl": "64px",
      "3xl": "22px",
      smi: "13px",
      sm: "14px",
      "19xl": "38px",
      "3xs": "10px",
      "21xl": "40px",
      "17xl": "36px",
      "lg-9": "18.9px",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
